### ISSUE TITLE
Se connecter

### ISSUE THREAD

**Issue by LangkaWS** [LangkaWS/sortir.com#1]
En tant qu'utilisateur, je peux me connecter sur la plateforme sortir.com avec un login (adresse mail ou pseudo) et un mot de passe.

Cas nominal : Suite à la saisie d'un login et mot de passe correct, j'accède à la plateforme.
Cas d'erreur : Suite à la saisie d'un login inconnu ou d'un mot de passe erroné, le site affiche un message d'erreur.

**Comment by Heroponne** [comment]
Ok !

**Comment by Neario** [comment]
Ok

**Comment by LangkaWS** [comment]
On doit pouvoir se connecter avec l'email et le username.
Idée : dans Authenticator::getUser : remplacer `$user = $this->entityManager->getRepository(User::class)->findOneBy(['email' => $credentials['email']]);` par `$user = $this->entityManager->getRepository(User::class)->findOneByEmailOrUsername(['id' => $credentials['id']]);`, changer tout ce qui fait référence à l'email par 'id' et créer une méthode dans le UserRepository :
```
findOneByEmailOrUsername(id)
{
    // Un truc du genre SELECT * FROM user WHERE user.username = 'id' OR user.email = 'id'
}
```
J'ai juste un problème si on a un utilisateur dont l'email est 'hello@hello.com' et un petit malin (qui n'est pas le même utilisateur) s'amuse à se mettre en username 'hello@hello.com'... Il faudrait restreindre le username à \d+ ?
