### ISSUE TITLE
Créer entité : User

### ISSUE THREAD

**Issue by LangkaWS** [LangkaWS/sortir.com#13]
- [x] userId : INT PRIMARY KEY NOT NULL AUTO-INC
- [x] userName : VARCHAR 30 NOT NULL
- [x] lastName : VARCHAR 30 NOT NULL
- [x] firstName : VARCHAR 30 NOT NULL
- [x] phone : VARCHAR 15
- [x] mail : VARCHAR 320 NOT NULL
- [x] password : VARCHAR 20 NOT NULL
- [x] isAdmin : BIT NOT NULL
- [x] isActive : BIT NOT NULL
- [x] profilePicture : VARCHAR 30
- [x] campus : CAMPUS NOT NULL RELATION MANYTOONE

**Comment by Heroponne** [comment]
ok !

**Comment by Neario** [comment]
parfait
