### ISSUE TITLE
Créer entité : Town

### ISSUE THREAD

**Issue by LangkaWS** [LangkaWS/sortir.com#15]
- [x] townId : INTEGER NOT NULL AUTO-INC PRIMARY KEY
- [x] name : VARCHAR 165 NOT NULL
- [x] zipCode : VARCHAR 10 NOT NULL

**Comment by LangkaWS** [comment]
- $townid : redondant avec $id qui est automatiquement créé
- $locations : relation ManyToMany -> OneToMany (une location ne peut n'avoir qu'une seule ville, une ville peut avoir plusieurs locations)

**Comment by LangkaWS** [comment]
Ok !

**Comment by Heroponne** [comment]
Ok !
