### ISSUE TITLE
Créer entité : Location

### ISSUE THREAD

**Issue by LangkaWS** [LangkaWS/sortir.com#16]
- [x] locationId : INTEGER NOT NULL AUTO-INC PRIMAY KEY
- [x] name : VARCHAR 30 NOT NULL
- [x] address : VARCHAR 50
- [x] town : TOWN NOT NULL RELATION MANYTOONE
- [x] latitude : FLOAT
- [x] longitude : FLOAT

**Comment by LangkaWS** [comment]
- $locationId : redondant avec $id (créé automatiquement)
- $town : relation ManyToMany -> ManyToOne  (plusieurs locations peuvent avoir la même ville, une location ne peut n'avoir qu'une seule ville)

**Comment by LangkaWS** [comment]
Ok !

**Comment by Heroponne** [comment]
Ok !
