### ISSUE TITLE
Créer Entity : Outing

### ISSUE THREAD

**Issue by Heroponne** [LangkaWS/sortir.com#18]
- [x] outingId: INT PRIMARY NOT NULL AUTO-INC
- [x] outingName: VARCHAR(30) NOT NULL
- [x] startDate: DATETIME NOT NULL
- [x] duration: INT
- [x] closingDate: DATETIME NOT NULL
- [x] maxParticipants: INT NOT NULL
- [x] description: TEXT (ou VARCHAR(500) si text pas ok)
- [x] state: STATE RELATION MANYTOONE NOT NULL
- [x] organizer: USER RELATION MANYTOONE NOT NULL
- [x] location: LOCATION RELATION MANYTOONE NOT NULL

**Comment by LangkaWS** [comment]
Pour $organizer et $participants, pourquoi il n'y a pas de inversedBy ? Pour pouvoir retrouver à partir de User si l'utilisateur organise des sorties ou y participent.
Avec doctrine, il m'a généré ce code pour ces 2 relations :
```
    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="organizedOutings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organizer;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="participatingOutings")
     */
    private $participants;
```

**Comment by LangkaWS** [comment]
Après réflexion, j'aurais remplacé closingDate par registrationDeadline, qui est plus explicite (comme c'est la date limite pour s'inscrire), c'est facilement remplaçable avec un petit ctrl + F au pire ^^

**Comment by Neario** [comment]
OK

**Comment by Neario** [comment]
Pareil j'ai ça pour $organizer er $participants
 ```
     /**
     * @ORM\ManyToOne(targetEntity=user::class, inversedBy="outings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organizer;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="outings")
     */
    private $participants;
```

**Comment by LangkaWS** [comment]
Ok !
