### ISSUE TITLE
Faire une page d'accueil

### ISSUE THREAD

**Issue by LangkaWS** [LangkaWS/sortir.com#23]

**Comment by LangkaWS** [comment]
MainController + home.html.twig

La page en elle-même reste à faire

**Comment by Neario** [comment]
Ok

**Comment by LangkaWS** [comment]
Reste à faire :
- [ ] Les autorisations sur les liens Action - Attente de #5, #6, #7, #9, afficher le détail d'une sortie, publier et modifier une sortie.
- [ ] Filtre - Attente de #4
